<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.3" release="Sat Mar 11 20:16:08 2017 -0800">
<training_set datafile="fasta_files/190215_YEP_Priority_List_Samples.bin20bp.hdp_input.txt_iter3K_eta1.5_topic169.txt" length="9">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="chr7_883081_883140" length="60" weight="1.000000" />
<sequence id="sequence_1" name="chr4_449771_449790" length="20" weight="1.000000" />
<sequence id="sequence_2" name="chr1_139941_139960" length="20" weight="1.000000" />
<sequence id="sequence_3" name="chr8_452181_452200" length="20" weight="1.000000" />
<sequence id="sequence_4" name="chr12_95991_96010" length="20" weight="1.000000" />
<sequence id="sequence_5" name="chr10_454031_454070" length="40" weight="1.000000" />
<sequence id="sequence_6" name="chr16_701771_701810" length="40" weight="1.000000" />
<sequence id="sequence_7" name="chr14_89461_89480" length="20" weight="1.000000" />
<sequence id="sequence_8" name="chr14_499921_499940" length="20" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.271</value>
<value letter_id="C">0.229</value>
<value letter_id="G">0.229</value>
<value letter_id="T">0.271</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme fasta_files/190215_YEP_Priority_List_Samples.bin20bp.hdp_input.txt_iter3K_eta1.5_topic169.txt -dna -mod zoops -oc meme_files/190215_YEP_Priority_List_Samples.bin20bp.hdp_input.txt_iter3K_eta1.5_topic169.meme -nmotifs 10 -minw 8 -maxw 20 -maxsize 500000 -revcomp </command_line>
<host>aci-lgn-003.acib.production.int.aci.ics.psu.edu</host>
<type>zoops</type>
<nmotifs>10</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>8</min_width>
<max_width>20</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>9</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>9</num_sequences>
<num_positions>260</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because couldn't find any more starting points for EM.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="A">0.271</value>
<value letter_id="C">0.229</value>
<value letter_id="G">0.229</value>
<value letter_id="T">0.271</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="11" sites="7" ic="13.2" re="13.3" llr="65" e_value="1.2e+000" bayes_threshold="5.79874" elapsed_time="0.030995">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">164</value>
<value letter_id="G">-945</value>
<value letter_id="T">8</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">32</value>
<value letter_id="G">-68</value>
<value letter_id="T">108</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">190</value>
<value letter_id="T">-92</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-68</value>
<value letter_id="G">190</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">188</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">108</value>
<value letter_id="C">-945</value>
<value letter_id="G">32</value>
<value letter_id="T">-92</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">140</value>
<value letter_id="C">-945</value>
<value letter_id="G">-945</value>
<value letter_id="T">8</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">90</value>
<value letter_id="G">132</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">8</value>
<value letter_id="C">-945</value>
<value letter_id="G">90</value>
<value letter_id="T">8</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">212</value>
<value letter_id="G">-945</value>
<value letter_id="T">-945</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-945</value>
<value letter_id="C">-68</value>
<value letter_id="G">-945</value>
<value letter_id="T">166</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.714286</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.285714</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.285714</value>
<value letter_id="G">0.142857</value>
<value letter_id="T">0.571429</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.857143</value>
<value letter_id="T">0.142857</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.142857</value>
<value letter_id="G">0.857143</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.571429</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.285714</value>
<value letter_id="T">0.142857</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.714286</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.285714</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.428571</value>
<value letter_id="G">0.571429</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.285714</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.428571</value>
<value letter_id="T">0.285714</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.142857</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.857143</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[CT][TC]GGT[AG][AT][GC][GAT]CT
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_2" position="6" strand="minus" pvalue="1.28e-06" >
<left_flank>GTA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>AACAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_6" position="3" strand="plus" pvalue="5.43e-06" >
<left_flank>AGT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GCTTTGGTCA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="40" strand="minus" pvalue="6.46e-06" >
<left_flank>GTAAGTTGA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTCAGAGTCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_5" position="9" strand="minus" pvalue="9.00e-06" >
<left_flank>TCTACCGGTG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>GTCGGTAAG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_4" position="4" strand="plus" pvalue="7.83e-05" >
<left_flank>TGAT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TACCA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_8" position="0" strand="minus" pvalue="9.69e-05" >
<left_flank>TTGTAACCC</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank></right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_3" position="8" strand="minus" pvalue="9.69e-05" >
<left_flank>T</left_flank>
<site>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TCATCAAG</right_flank>
</contributing_site>
</contributing_sites>
</motif>
<motif id="motif_2" name="2" width="8" sites="2" ic="15.0" re="15.3" llr="21" e_value="7.8e+003" bayes_threshold="6.60733" elapsed_time="0.044993">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">88</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">88</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">188</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.500000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.500000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
GG[AT]TGGGA
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_5" position="30" strand="plus" pvalue="2.51e-05" >
<left_flank>CACCGGTAGA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>TG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="25" strand="plus" pvalue="2.51e-05" >
<left_flank>AGACATCGAC</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
</site>
<right_flank>CTCTGAAAGC</right_flank>
</contributing_site>
</contributing_sites>
</motif>
<motif id="motif_3" name="3" width="10" sites="2" ic="17.0" re="17.1" llr="24" e_value="2.3e+004" bayes_threshold="6.46761" elapsed_time="0.057991">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">188</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">212</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">112</value>
<value letter_id="G">112</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">88</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">88</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">88</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">88</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">212</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">1.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.500000</value>
<value letter_id="G">0.500000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.500000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.500000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.500000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.500000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
GTCAA[CG][AT][AT]CG
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_6" position="20" strand="plus" pvalue="7.36e-06" >
<left_flank>CGCTGCTTTG</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>TTCCATCTAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="4" strand="plus" pvalue="7.36e-06" >
<left_flank>TCAA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>GAGACATCGA</right_flank>
</contributing_site>
</contributing_sites>
</motif>
<motif id="motif_4" name="4" width="9" sites="2" ic="14.0" re="13.9" llr="19" e_value="7.9e+004" bayes_threshold="6.53916" elapsed_time="0.067990">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">88</value>
<value letter_id="C">-765</value>
<value letter_id="G">112</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">88</value>
<value letter_id="C">112</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">188</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">88</value>
<value letter_id="C">-765</value>
<value letter_id="G">-765</value>
<value letter_id="T">88</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">112</value>
<value letter_id="G">112</value>
<value letter_id="T">-765</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-765</value>
<value letter_id="C">-765</value>
<value letter_id="G">212</value>
<value letter_id="T">-765</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.500000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.500000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.500000</value>
<value letter_id="C">0.500000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">1.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.500000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.500000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.500000</value>
<value letter_id="G">0.500000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
GA[AG]A[AC]A[AT][CG]G
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_0" position="14" strand="plus" pvalue="1.36e-05" >
<left_flank>GTCAACAACG</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>ACGGTTGGGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_7" position="3" strand="minus" pvalue="6.48e-05" >
<left_flank>CACGCCCA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>