<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.3" release="Sat Mar 11 20:16:08 2017 -0800">
<training_set datafile="fasta_files/190215_YEP_Priority_List_Samples.bin20bp.hdp_input.txt_iter3K_eta1.5_topic65.txt" length="370">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="chr7_255041_255100" length="60" weight="1.000000" />
<sequence id="sequence_1" name="chr7_311671_311730" length="60" weight="1.000000" />
<sequence id="sequence_2" name="chr7_346361_346430" length="70" weight="1.000000" />
<sequence id="sequence_3" name="chr7_371341_371400" length="60" weight="1.000000" />
<sequence id="sequence_4" name="chr7_384751_384820" length="70" weight="1.000000" />
<sequence id="sequence_5" name="chr7_398001_398070" length="70" weight="1.000000" />
<sequence id="sequence_6" name="chr7_413461_413520" length="60" weight="1.000000" />
<sequence id="sequence_7" name="chr7_439531_439590" length="60" weight="1.000000" />
<sequence id="sequence_8" name="chr7_480081_480140" length="60" weight="1.000000" />
<sequence id="sequence_9" name="chr7_480391_480450" length="60" weight="1.000000" />
<sequence id="sequence_10" name="chr7_480671_480740" length="70" weight="1.000000" />
<sequence id="sequence_11" name="chr7_480951_481020" length="70" weight="1.000000" />
<sequence id="sequence_12" name="chr7_481261_481320" length="60" weight="1.000000" />
<sequence id="sequence_13" name="chr7_481661_481730" length="70" weight="1.000000" />
<sequence id="sequence_14" name="chr7_481981_482050" length="70" weight="1.000000" />
<sequence id="sequence_15" name="chr7_482461_482520" length="60" weight="1.000000" />
<sequence id="sequence_16" name="chr7_483551_483620" length="70" weight="1.000000" />
<sequence id="sequence_17" name="chr7_483681_483750" length="70" weight="1.000000" />
<sequence id="sequence_18" name="chr7_516391_516440" length="50" weight="1.000000" />
<sequence id="sequence_19" name="chr7_557831_557890" length="60" weight="1.000000" />
<sequence id="sequence_20" name="chr7_609881_609940" length="60" weight="1.000000" />
<sequence id="sequence_21" name="chr7_625281_625340" length="60" weight="1.000000" />
<sequence id="sequence_22" name="chr7_703021_703070" length="50" weight="1.000000" />
<sequence id="sequence_23" name="chr7_766261_766310" length="50" weight="1.000000" />
<sequence id="sequence_24" name="chr7_809671_809740" length="70" weight="1.000000" />
<sequence id="sequence_25" name="chr7_882701_882750" length="50" weight="1.000000" />
<sequence id="sequence_26" name="chr7_882991_883050" length="60" weight="1.000000" />
<sequence id="sequence_27" name="chr7_883171_883220" length="50" weight="1.000000" />
<sequence id="sequence_28" name="chr7_883491_883560" length="70" weight="1.000000" />
<sequence id="sequence_29" name="chr7_914981_915030" length="50" weight="1.000000" />
<sequence id="sequence_30" name="chr7_977051_977110" length="60" weight="1.000000" />
<sequence id="sequence_31" name="chr7_986961_987020" length="60" weight="1.000000" />
<sequence id="sequence_32" name="chr7_987191_987250" length="60" weight="1.000000" />
<sequence id="sequence_33" name="chr7_987491_987540" length="50" weight="1.000000" />
<sequence id="sequence_34" name="chr7_990141_990160" length="20" weight="1.000000" />
<sequence id="sequence_35" name="chr7_1050381_1050430" length="50" weight="1.000000" />
<sequence id="sequence_36" name="chr6_95661_95770" length="110" weight="1.000000" />
<sequence id="sequence_37" name="chr6_106681_106750" length="70" weight="1.000000" />
<sequence id="sequence_38" name="chr6_220731_220800" length="70" weight="1.000000" />
<sequence id="sequence_39" name="chr6_225011_225080" length="70" weight="1.000000" />
<sequence id="sequence_40" name="chr5_23681_23740" length="60" weight="1.000000" />
<sequence id="sequence_41" name="chr5_42261_42320" length="60" weight="1.000000" />
<sequence id="sequence_42" name="chr5_67981_68040" length="60" weight="1.000000" />
<sequence id="sequence_43" name="chr5_69191_69250" length="60" weight="1.000000" />
<sequence id="sequence_44" name="chr5_77661_77730" length="70" weight="1.000000" />
<sequence id="sequence_45" name="chr5_85251_85310" length="60" weight="1.000000" />
<sequence id="sequence_46" name="chr5_85851_85910" length="60" weight="1.000000" />
<sequence id="sequence_47" name="chr5_140641_140700" length="60" weight="1.000000" />
<sequence id="sequence_48" name="chr5_141241_141300" length="60" weight="1.000000" />
<sequence id="sequence_49" name="chr5_152651_152710" length="60" weight="1.000000" />
<sequence id="sequence_50" name="chr5_153101_153160" length="60" weight="1.000000" />
<sequence id="sequence_51" name="chr5_174811_174870" length="60" weight="1.000000" />
<sequence id="sequence_52" name="chr5_221641_221700" length="60" weight="1.000000" />
<sequence id="sequence_53" name="chr5_225531_225600" length="70" weight="1.000000" />
<sequence id="sequence_54" name="chr5_242111_242170" length="60" weight="1.000000" />
<sequence id="sequence_55" name="chr5_266271_266320" length="50" weight="1.000000" />
<sequence id="sequence_56" name="chr5_268421_268490" length="70" weight="1.000000" />
<sequence id="sequence_57" name="chr5_305961_306020" length="60" weight="1.000000" />
<sequence id="sequence_58" name="chr5_363501_363530" length="30" weight="1.000000" />
<sequence id="sequence_59" name="chr5_461971_462030" length="60" weight="1.000000" />
<sequence id="sequence_60" name="chr5_491221_491280" length="60" weight="1.000000" />
<sequence id="sequence_61" name="chr4_10201_10260" length="60" weight="1.000000" />
<sequence id="sequence_62" name="chr4_13751_13790" length="40" weight="1.000000" />
<sequence id="sequence_63" name="chr4_45271_45330" length="60" weight="1.000000" />
<sequence id="sequence_64" name="chr4_76961_77020" length="60" weight="1.000000" />
<sequence id="sequence_65" name="chr4_132831_132890" length="60" weight="1.000000" />
<sequence id="sequence_66" name="chr4_156111_156170" length="60" weight="1.000000" />
<sequence id="sequence_67" name="chr4_323081_323140" length="60" weight="1.000000" />
<sequence id="sequence_68" name="chr4_386981_387030" length="50" weight="1.000000" />
<sequence id="sequence_69" name="chr4_411441_411500" length="60" weight="1.000000" />
<sequence id="sequence_70" name="chr4_449821_449870" length="50" weight="1.000000" />
<sequence id="sequence_71" name="chr4_465311_465370" length="60" weight="1.000000" />
<sequence id="sequence_72" name="chr4_472461_472530" length="70" weight="1.000000" />
<sequence id="sequence_73" name="chr4_537001_537020" length="20" weight="1.000000" />
<sequence id="sequence_74" name="chr4_539081_539150" length="70" weight="1.000000" />
<sequence id="sequence_75" name="chr4_543761_543820" length="60" weight="1.000000" />
<sequence id="sequence_76" name="chr4_555931_555990" length="60" weight="1.000000" />
<sequence id="sequence_77" name="chr4_580161_580220" length="60" weight="1.000000" />
<sequence id="sequence_78" name="chr4_591751_591810" length="60" weight="1.000000" />
<sequence id="sequence_79" name="chr4_600001_600060" length="60" weight="1.000000" />
<sequence id="sequence_80" name="chr4_721901_721950" length="50" weight="1.000000" />
<sequence id="sequence_81" name="chr4_722581_722640" length="60" weight="1.000000" />
<sequence id="sequence_82" name="chr4_835941_836010" length="70" weight="1.000000" />
<sequence id="sequence_83" name="chr4_976291_976350" length="60" weight="1.000000" />
<sequence id="sequence_84" name="chr4_976661_976720" length="60" weight="1.000000" />
<sequence id="sequence_85" name="chr4_1080621_1080680" length="60" weight="1.000000" />
<sequence id="sequence_86" name="chr4_1161701_1161750" length="50" weight="1.000000" />
<sequence id="sequence_87" name="chr4_1245051_1245110" length="60" weight="1.000000" />
<sequence id="sequence_88" name="chr4_1278821_1278880" length="60" weight="1.000000" />
<sequence id="sequence_89" name="chr4_1345431_1345490" length="60" weight="1.000000" />
<sequence id="sequence_90" name="chr4_1362431_1362490" length="60" weight="1.000000" />
<sequence id="sequence_91" name="chr4_1489621_1489680" length="60" weight="1.000000" />
<sequence id="sequence_92" name="chr4_1490201_1490250" length="50" weight="1.000000" />
<sequence id="sequence_93" name="chr3_78541_78590" length="50" weight="1.000000" />
<sequence id="sequence_94" name="chr3_138041_138110" length="70" weight="1.000000" />
<sequence id="sequence_95" name="chr3_138481_138540" length="60" weight="1.000000" />
<sequence id="sequence_96" name="chr3_138771_138830" length="60" weight="1.000000" />
<sequence id="sequence_97" name="chr3_163621_163690" length="70" weight="1.000000" />
<sequence id="sequence_98" name="chr3_177701_177760" length="60" weight="1.000000" />
<sequence id="sequence_99" name="chr3_197401_197460" length="60" weight="1.000000" />
<sequence id="sequence_100" name="chr2_88691_88730" length="40" weight="1.000000" />
<sequence id="sequence_101" name="chr2_136101_136170" length="70" weight="1.000000" />
<sequence id="sequence_102" name="chr2_140591_140660" length="70" weight="1.000000" />
<sequence id="sequence_103" name="chr2_165261_165320" length="60" weight="1.000000" />
<sequence id="sequence_104" name="chr2_281051_281110" length="60" weight="1.000000" />
<sequence id="sequence_105" name="chr2_300741_300800" length="60" weight="1.000000" />
<sequence id="sequence_106" name="chr2_301061_301120" length="60" weight="1.000000" />
<sequence id="sequence_107" name="chr2_373281_373340" length="60" weight="1.000000" />
<sequence id="sequence_108" name="chr2_408691_408760" length="70" weight="1.000000" />
<sequence id="sequence_109" name="chr2_474121_474180" length="60" weight="1.000000" />
<sequence id="sequence_110" name="chr2_477941_477960" length="20" weight="1.000000" />
<sequence id="sequence_111" name="chr2_478301_478360" length="60" weight="1.000000" />
<sequence id="sequence_112" name="chr2_478771_478790" length="20" weight="1.000000" />
<sequence id="sequence_113" name="chr2_554921_554980" length="60" weight="1.000000" />
<sequence id="sequence_114" name="chr2_556031_556090" length="60" weight="1.000000" />
<sequence id="sequence_115" name="chr2_605411_605470" length="60" weight="1.000000" />
<sequence id="sequence_116" name="chr2_625001_625070" length="70" weight="1.000000" />
<sequence id="sequence_117" name="chr2_642711_642780" length="70" weight="1.000000" />
<sequence id="sequence_118" name="chr2_680421_680480" length="60" weight="1.000000" />
<sequence id="sequence_119" name="chr2_681371_681440" length="70" weight="1.000000" />
<sequence id="sequence_120" name="chr1_34481_34540" length="60" weight="1.000000" />
<sequence id="sequence_121" name="chr1_68411_68470" length="60" weight="1.000000" />
<sequence id="sequence_122" name="chr1_68701_68760" length="60" weight="1.000000" />
<sequence id="sequence_123" name="chr1_72091_72140" length="50" weight="1.000000" />
<sequence id="sequence_124" name="chr1_72521_72590" length="70" weight="1.000000" />
<sequence id="sequence_125" name="chr1_73031_73080" length="50" weight="1.000000" />
<sequence id="sequence_126" name="chr1_141741_141790" length="50" weight="1.000000" />
<sequence id="sequence_127" name="chr1_142881_142940" length="60" weight="1.000000" />
<sequence id="sequence_128" name="chr1_190021_190080" length="60" weight="1.000000" />
<sequence id="sequence_129" name="chr9_18961_19020" length="60" weight="1.000000" />
<sequence id="sequence_130" name="chr9_21971_22030" length="60" weight="1.000000" />
<sequence id="sequence_131" name="chr9_22361_22430" length="70" weight="1.000000" />
<sequence id="sequence_132" name="chr9_25481_25530" length="50" weight="1.000000" />
<sequence id="sequence_133" name="chr9_130041_130110" length="70" weight="1.000000" />
<sequence id="sequence_134" name="chr9_138261_138320" length="60" weight="1.000000" />
<sequence id="sequence_135" name="chr9_138591_138660" length="70" weight="1.000000" />
<sequence id="sequence_136" name="chr9_139291_139340" length="50" weight="1.000000" />
<sequence id="sequence_137" name="chr9_177771_177840" length="70" weight="1.000000" />
<sequence id="sequence_138" name="chr9_255551_255620" length="70" weight="1.000000" />
<sequence id="sequence_139" name="chr9_268091_268150" length="60" weight="1.000000" />
<sequence id="sequence_140" name="chr9_317631_317700" length="70" weight="1.000000" />
<sequence id="sequence_141" name="chr9_386741_386800" length="60" weight="1.000000" />
<sequence id="sequence_142" name="chr9_388401_388450" length="50" weight="1.000000" />
<sequence id="sequence_143" name="chr9_394911_394960" length="50" weight="1.000000" />
<sequence id="sequence_144" name="chr9_408051_408110" length="60" weight="1.000000" />
<sequence id="sequence_145" name="chr9_415721_415830" length="110" weight="1.000000" />
<sequence id="sequence_146" name="chr8_34621_34680" length="60" weight="1.000000" />
<sequence id="sequence_147" name="chr8_34881_34940" length="60" weight="1.000000" />
<sequence id="sequence_148" name="chr8_35401_35460" length="60" weight="1.000000" />
<sequence id="sequence_149" name="chr8_35691_35740" length="50" weight="1.000000" />
<sequence id="sequence_150" name="chr8_48371_48430" length="60" weight="1.000000" />
<sequence id="sequence_151" name="chr8_74631_74700" length="70" weight="1.000000" />
<sequence id="sequence_152" name="chr8_115261_115320" length="60" weight="1.000000" />
<sequence id="sequence_153" name="chr8_122351_122410" length="60" weight="1.000000" />
<sequence id="sequence_154" name="chr8_175161_175220" length="60" weight="1.000000" />
<sequence id="sequence_155" name="chr8_361841_361910" length="70" weight="1.000000" />
<sequence id="sequence_156" name="chr8_375111_375170" length="60" weight="1.000000" />
<sequence id="sequence_157" name="chr8_381811_381870" length="60" weight="1.000000" />
<sequence id="sequence_158" name="chr8_451571_451630" length="60" weight="1.000000" />
<sequence id="sequence_159" name="chr8_452061_452120" length="60" weight="1.000000" />
<sequence id="sequence_160" name="chr8_452401_452450" length="50" weight="1.000000" />
<sequence id="sequence_161" name="chr8_455741_455790" length="50" weight="1.000000" />
<sequence id="sequence_162" name="chr8_504491_504560" length="70" weight="1.000000" />
<sequence id="sequence_163" name="chr8_538071_538090" length="20" weight="1.000000" />
<sequence id="sequence_164" name="chr13_24291_24340" length="50" weight="1.000000" />
<sequence id="sequence_165" name="chr13_24781_24840" length="60" weight="1.000000" />
<sequence id="sequence_166" name="chr13_24931_24950" length="20" weight="1.000000" />
<sequence id="sequence_167" name="chr13_25251_25320" length="70" weight="1.000000" />
<sequence id="sequence_168" name="chr13_26351_26420" length="70" weight="1.000000" />
<sequence id="sequence_169" name="chr13_253441_253480" length="40" weight="1.000000" />
<sequence id="sequence_170" name="chr13_268071_268120" length="50" weight="1.000000" />
<sequence id="sequence_171" name="chr13_287611_287660" length="50" weight="1.000000" />
<sequence id="sequence_172" name="chr13_298161_298210" length="50" weight="1.000000" />
<sequence id="sequence_173" name="chr13_298391_298450" length="60" weight="1.000000" />
<sequence id="sequence_174" name="chr13_298691_298750" length="60" weight="1.000000" />
<sequence id="sequence_175" name="chr13_302961_303020" length="60" weight="1.000000" />
<sequence id="sequence_176" name="chr13_306231_306280" length="50" weight="1.000000" />
<sequence id="sequence_177" name="chr13_306691_306750" length="60" weight="1.000000" />
<sequence id="sequence_178" name="chr13_347231_347290" length="60" weight="1.000000" />
<sequence id="sequence_179" name="chr13_388161_388220" length="60" weight="1.000000" />
<sequence id="sequence_180" name="chr13_388421_388480" length="60" weight="1.000000" />
<sequence id="sequence_181" name="chr13_408601_408660" length="60" weight="1.000000" />
<sequence id="sequence_182" name="chr13_473071_473140" length="70" weight="1.000000" />
<sequence id="sequence_183" name="chr13_499571_499630" length="60" weight="1.000000" />
<sequence id="sequence_184" name="chr13_540181_540250" length="70" weight="1.000000" />
<sequence id="sequence_185" name="chr13_540561_540620" length="60" weight="1.000000" />
<sequence id="sequence_186" name="chr13_551531_551590" length="60" weight="1.000000" />
<sequence id="sequence_187" name="chr13_557131_557190" length="60" weight="1.000000" />
<sequence id="sequence_188" name="chr13_637191_637260" length="70" weight="1.000000" />
<sequence id="sequence_189" name="chr13_652601_652660" length="60" weight="1.000000" />
<sequence id="sequence_190" name="chr13_653641_653700" length="60" weight="1.000000" />
<sequence id="sequence_191" name="chr13_661841_661880" length="40" weight="1.000000" />
<sequence id="sequence_192" name="chr13_751421_751480" length="60" weight="1.000000" />
<sequence id="sequence_193" name="chr13_774411_774480" length="70" weight="1.000000" />
<sequence id="sequence_194" name="chr13_861261_861300" length="40" weight="1.000000" />
<sequence id="sequence_195" name="chr13_872771_872820" length="50" weight="1.000000" />
<sequence id="sequence_196" name="chr13_880661_880710" length="50" weight="1.000000" />
<sequence id="sequence_197" name="chr12_84201_84270" length="70" weight="1.000000" />
<sequence id="sequence_198" name="chr12_86981_87040" length="60" weight="1.000000" />
<sequence id="sequence_199" name="chr12_125221_125280" length="60" weight="1.000000" />
<sequence id="sequence_200" name="chr12_199381_199440" length="60" weight="1.000000" />
<sequence id="sequence_201" name="chr12_202121_202180" length="60" weight="1.000000" />
<sequence id="sequence_202" name="chr12_232461_232520" length="60" weight="1.000000" />
<sequence id="sequence_203" name="chr12_232791_232850" length="60" weight="1.000000" />
<sequence id="sequence_204" name="chr12_233041_233100" length="60" weight="1.000000" />
<sequence id="sequence_205" name="chr12_233321_233380" length="60" weight="1.000000" />
<sequence id="sequence_206" name="chr12_233691_233750" length="60" weight="1.000000" />
<sequence id="sequence_207" name="chr12_234661_234710" length="50" weight="1.000000" />
<sequence id="sequence_208" name="chr12_253441_253490" length="50" weight="1.000000" />
<sequence id="sequence_209" name="chr12_283281_283340" length="60" weight="1.000000" />
<sequence id="sequence_210" name="chr12_369821_369880" length="60" weight="1.000000" />
<sequence id="sequence_211" name="chr12_370591_370650" length="60" weight="1.000000" />
<sequence id="sequence_212" name="chr12_370731_370800" length="70" weight="1.000000" />
<sequence id="sequence_213" name="chr12_424231_424300" length="70" weight="1.000000" />
<sequence id="sequence_214" name="chr12_472371_472420" length="50" weight="1.000000" />
<sequence id="sequence_215" name="chr12_481961_482010" length="50" weight="1.000000" />
<sequence id="sequence_216" name="chr12_485551_485570" length="20" weight="1.000000" />
<sequence id="sequence_217" name="chr12_485661_485710" length="50" weight="1.000000" />
<sequence id="sequence_218" name="chr12_499191_499250" length="60" weight="1.000000" />
<sequence id="sequence_219" name="chr12_637231_637290" length="60" weight="1.000000" />
<sequence id="sequence_220" name="chr12_637661_637730" length="70" weight="1.000000" />
<sequence id="sequence_221" name="chr12_638091_638150" length="60" weight="1.000000" />
<sequence id="sequence_222" name="chr12_638411_638470" length="60" weight="1.000000" />
<sequence id="sequence_223" name="chr12_639041_639110" length="70" weight="1.000000" />
<sequence id="sequence_224" name="chr12_639651_639710" length="60" weight="1.000000" />
<sequence id="sequence_225" name="chr12_704481_704550" length="70" weight="1.000000" />
<sequence id="sequence_226" name="chr12_710721_710790" length="70" weight="1.000000" />
<sequence id="sequence_227" name="chr12_728361_728430" length="70" weight="1.000000" />
<sequence id="sequence_228" name="chr12_737871_737940" length="70" weight="1.000000" />
<sequence id="sequence_229" name="chr12_806651_806710" length="60" weight="1.000000" />
<sequence id="sequence_230" name="chr12_809381_809440" length="60" weight="1.000000" />
<sequence id="sequence_231" name="chr12_837731_837780" length="50" weight="1.000000" />
<sequence id="sequence_232" name="chr12_838271_838330" length="60" weight="1.000000" />
<sequence id="sequence_233" name="chr12_838771_838840" length="70" weight="1.000000" />
<sequence id="sequence_234" name="chr12_1012211_1012280" length="70" weight="1.000000" />
<sequence id="sequence_235" name="chr11_67871_67930" length="60" weight="1.000000" />
<sequence id="sequence_236" name="chr11_68301_68360" length="60" weight="1.000000" />
<sequence id="sequence_237" name="chr11_99841_99890" length="50" weight="1.000000" />
<sequence id="sequence_238" name="chr11_163861_163920" length="60" weight="1.000000" />
<sequence id="sequence_239" name="chr11_231411_231480" length="70" weight="1.000000" />
<sequence id="sequence_240" name="chr11_258741_258800" length="60" weight="1.000000" />
<sequence id="sequence_241" name="chr11_260701_260770" length="70" weight="1.000000" />
<sequence id="sequence_242" name="chr11_284011_284070" length="60" weight="1.000000" />
<sequence id="sequence_243" name="chr11_284211_284270" length="60" weight="1.000000" />
<sequence id="sequence_244" name="chr11_326621_326680" length="60" weight="1.000000" />
<sequence id="sequence_245" name="chr11_327111_327170" length="60" weight="1.000000" />
<sequence id="sequence_246" name="chr11_355541_355600" length="60" weight="1.000000" />
<sequence id="sequence_247" name="chr11_355741_355800" length="60" weight="1.000000" />
<sequence id="sequence_248" name="chr11_355971_356040" length="70" weight="1.000000" />
<sequence id="sequence_249" name="chr11_514411_514480" length="70" weight="1.000000" />
<sequence id="sequence_250" name="chr11_514621_514680" length="60" weight="1.000000" />
<sequence id="sequence_251" name="chr11_517411_517460" length="50" weight="1.000000" />
<sequence id="sequence_252" name="chr11_517941_518000" length="60" weight="1.000000" />
<sequence id="sequence_253" name="chr11_518951_519060" length="110" weight="1.000000" />
<sequence id="sequence_254" name="chr11_614911_615000" length="90" weight="1.000000" />
<sequence id="sequence_255" name="chr11_630561_630620" length="60" weight="1.000000" />
<sequence id="sequence_256" name="chr10_18941_19010" length="70" weight="1.000000" />
<sequence id="sequence_257" name="chr10_69101_69170" length="70" weight="1.000000" />
<sequence id="sequence_258" name="chr10_74291_74350" length="60" weight="1.000000" />
<sequence id="sequence_259" name="chr10_120831_120900" length="70" weight="1.000000" />
<sequence id="sequence_260" name="chr10_123241_123280" length="40" weight="1.000000" />
<sequence id="sequence_261" name="chr10_123591_123650" length="60" weight="1.000000" />
<sequence id="sequence_262" name="chr10_139541_139600" length="60" weight="1.000000" />
<sequence id="sequence_263" name="chr10_173201_173290" length="90" weight="1.000000" />
<sequence id="sequence_264" name="chr10_195431_195490" length="60" weight="1.000000" />
<sequence id="sequence_265" name="chr10_211701_211770" length="70" weight="1.000000" />
<sequence id="sequence_266" name="chr10_220391_220410" length="20" weight="1.000000" />
<sequence id="sequence_267" name="chr10_227971_228020" length="50" weight="1.000000" />
<sequence id="sequence_268" name="chr10_291221_291280" length="60" weight="1.000000" />
<sequence id="sequence_269" name="chr10_391991_392050" length="60" weight="1.000000" />
<sequence id="sequence_270" name="chr10_453771_453830" length="60" weight="1.000000" />
<sequence id="sequence_271" name="chr10_454121_454170" length="50" weight="1.000000" />