<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence*, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter*)>
<!ATTLIST alphabet name CDATA #REQUIRED>
<!ELEMENT ambigs (letter*)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ATTLIST letter equals CDATA #IMPLIED>
<!ATTLIST letter aliases CDATA #IMPLIED>
<!ATTLIST letter complement CDATA #IMPLIED>
<!ATTLIST letter name CDATA #IMPLIED>
<!ATTLIST letter colour CDATA #IMPLIED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  spfun,
  min_width,
  max_width,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  hsfrac,
  maxwords,
  maxsize,
  csites,
  strands,
  priors_file,
  reason_for_stopping,
  back_order,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT spfun (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT hsfrac (#PCDATA)*>
<!ELEMENT maxwords (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT csites (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT back_order (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif*)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
                url CDATA ""
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site*)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref*)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites*)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value*)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array*)>

]>
<!-- Begin document body -->
<MEME version="4.11.3" release="Sat Mar 11 20:16:08 2017 -0800">
<training_set datafile="fasta_files/190215_YEP_Priority_List_Samples.bin20bp.hdp_input.txt_iter3K_eta1.5_topic34.txt" length="46">
<alphabet name="DNA" like="dna">
<letter id="A" symbol="A" complement="T" name="Adenine" colour="CC0000"/>
<letter id="C" symbol="C" complement="G" name="Cytosine" colour="0000CC"/>
<letter id="G" symbol="G" complement="C" name="Guanine" colour="FFB300"/>
<letter id="T" symbol="T" aliases="U" complement="A" name="Thymine" colour="008000"/>
<letter id="N" symbol="N" aliases="X." equals="ACGT" name="Any base"/>
<letter id="V" symbol="V" equals="ACG" name="Not T"/>
<letter id="H" symbol="H" equals="ACT" name="Not G"/>
<letter id="D" symbol="D" equals="AGT" name="Not C"/>
<letter id="B" symbol="B" equals="CGT" name="Not A"/>
<letter id="M" symbol="M" equals="AC" name="Amino"/>
<letter id="R" symbol="R" equals="AG" name="Purine"/>
<letter id="W" symbol="W" equals="AT" name="Weak"/>
<letter id="S" symbol="S" equals="CG" name="Strong"/>
<letter id="Y" symbol="Y" equals="CT" name="Pyrimidine"/>
<letter id="K" symbol="K" equals="GT" name="Keto"/>
</alphabet>
<sequence id="sequence_0" name="chr7_271551_271610" length="60" weight="1.000000" />
<sequence id="sequence_1" name="chr7_478231_478290" length="60" weight="1.000000" />
<sequence id="sequence_2" name="chr7_478461_478530" length="70" weight="1.000000" />
<sequence id="sequence_3" name="chr7_478801_478900" length="100" weight="1.000000" />
<sequence id="sequence_4" name="chr7_479181_479250" length="70" weight="1.000000" />
<sequence id="sequence_5" name="chr7_479471_479540" length="70" weight="1.000000" />
<sequence id="sequence_6" name="chr7_479721_479790" length="70" weight="1.000000" />
<sequence id="sequence_7" name="chr7_479981_480050" length="70" weight="1.000000" />
<sequence id="sequence_8" name="chr7_480351_480410" length="60" weight="1.000000" />
<sequence id="sequence_9" name="chr7_483481_483510" length="30" weight="1.000000" />
<sequence id="sequence_10" name="chr7_785611_785680" length="70" weight="1.000000" />
<sequence id="sequence_11" name="chr6_95331_95400" length="70" weight="1.000000" />
<sequence id="sequence_12" name="chr6_95611_95670" length="60" weight="1.000000" />
<sequence id="sequence_13" name="chr6_225121_225190" length="70" weight="1.000000" />
<sequence id="sequence_14" name="chr5_69161_69210" length="50" weight="1.000000" />
<sequence id="sequence_15" name="chr5_140631_140700" length="70" weight="1.000000" />
<sequence id="sequence_16" name="chr5_152661_152720" length="60" weight="1.000000" />
<sequence id="sequence_17" name="chr5_303511_303580" length="70" weight="1.000000" />
<sequence id="sequence_18" name="chr5_466761_466780" length="20" weight="1.000000" />
<sequence id="sequence_19" name="chr4_1169111_1169130" length="20" weight="1.000000" />
<sequence id="sequence_20" name="chr4_1490281_1490330" length="50" weight="1.000000" />
<sequence id="sequence_21" name="chr2_61011_61030" length="20" weight="1.000000" />
<sequence id="sequence_22" name="chr2_165161_165280" length="120" weight="1.000000" />
<sequence id="sequence_23" name="chr2_376041_376100" length="60" weight="1.000000" />
<sequence id="sequence_24" name="chr2_408691_408750" length="60" weight="1.000000" />
<sequence id="sequence_25" name="chr9_139321_139380" length="60" weight="1.000000" />
<sequence id="sequence_26" name="chr8_517111_517180" length="70" weight="1.000000" />
<sequence id="sequence_27" name="chr8_517351_517420" length="70" weight="1.000000" />
<sequence id="sequence_28" name="chr13_483581_483650" length="70" weight="1.000000" />
<sequence id="sequence_29" name="chr13_540491_540560" length="70" weight="1.000000" />
<sequence id="sequence_30" name="chr13_852101_852170" length="70" weight="1.000000" />
<sequence id="sequence_31" name="chr12_839481_839550" length="70" weight="1.000000" />
<sequence id="sequence_32" name="chr12_839591_839660" length="70" weight="1.000000" />
<sequence id="sequence_33" name="chr12_1012221_1012270" length="50" weight="1.000000" />
<sequence id="sequence_34" name="chr11_216861_216930" length="70" weight="1.000000" />
<sequence id="sequence_35" name="chr11_217001_217070" length="70" weight="1.000000" />
<sequence id="sequence_36" name="chr11_518951_518990" length="40" weight="1.000000" />
<sequence id="sequence_37" name="chr10_466351_466420" length="70" weight="1.000000" />
<sequence id="sequence_38" name="chr16_40471_40530" length="60" weight="1.000000" />
<sequence id="sequence_39" name="chr16_214841_214910" length="70" weight="1.000000" />
<sequence id="sequence_40" name="chr15_522721_522790" length="70" weight="1.000000" />
<sequence id="sequence_41" name="chr15_762231_762300" length="70" weight="1.000000" />
<sequence id="sequence_42" name="chr15_832241_832300" length="60" weight="1.000000" />
<sequence id="sequence_43" name="chr15_1043411_1043480" length="70" weight="1.000000" />
<sequence id="sequence_44" name="chr14_198301_198360" length="60" weight="1.000000" />
<sequence id="sequence_45" name="chr14_427161_427230" length="70" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="A">0.256</value>
<value letter_id="C">0.244</value>
<value letter_id="G">0.244</value>
<value letter_id="T">0.256</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme fasta_files/190215_YEP_Priority_List_Samples.bin20bp.hdp_input.txt_iter3K_eta1.5_topic34.txt -dna -mod zoops -oc meme_files/190215_YEP_Priority_List_Samples.bin20bp.hdp_input.txt_iter3K_eta1.5_topic34.meme -nmotifs 10 -minw 8 -maxw 20 -maxsize 500000 -revcomp </command_line>
<host>aci-lgn-003.acib.production.int.aci.ics.psu.edu</host>
<type>zoops</type>
<nmotifs>10</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<use_llr>0</use_llr>
<min_width>8</min_width>
<max_width>20</max_width>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<substring>yes</substring>
<minsites>2</minsites>
<maxsites>46</maxsites>
<wnsites>0.8</wnsites>
<spmap>uni</spmap>
<spfuzz>0.5</spfuzz>
<prior>dirichlet</prior>
<beta>0.01</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>46</num_sequences>
<num_positions>2910</num_positions>
<seed>0</seed>
<ctfrac>-1</ctfrac>
<maxwords>-1</maxwords>
<strands>both</strands>
<priors_file></priors_file>
<reason_for_stopping>Stopped because requested number of motifs (10) found.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="A">0.256</value>
<value letter_id="C">0.244</value>
<value letter_id="G">0.244</value>
<value letter_id="T">0.256</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="12" sites="22" ic="15.4" re="15.6" llr="238" e_value="3.5e-020" bayes_threshold="7.79177" elapsed_time="1.395788">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">166</value>
<value letter_id="G">-10</value>
<value letter_id="T">-1110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">203</value>
<value letter_id="G">-1110</value>
<value letter_id="T">-1110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">-1110</value>
<value letter_id="G">203</value>
<value letter_id="T">-1110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">-1110</value>
<value letter_id="G">182</value>
<value letter_id="T">-91</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">-142</value>
<value letter_id="G">-242</value>
<value letter_id="T">175</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">121</value>
<value letter_id="C">-43</value>
<value letter_id="G">-1110</value>
<value letter_id="T">-17</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-91</value>
<value letter_id="C">157</value>
<value letter_id="G">-84</value>
<value letter_id="T">-1110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-49</value>
<value letter_id="C">174</value>
<value letter_id="G">-1110</value>
<value letter_id="T">-1110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">-1110</value>
<value letter_id="G">203</value>
<value letter_id="T">-1110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">90</value>
<value letter_id="G">116</value>
<value letter_id="T">-1110</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">74</value>
<value letter_id="G">-1110</value>
<value letter_id="T">121</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1110</value>
<value letter_id="C">116</value>
<value letter_id="G">16</value>
<value letter_id="T">-49</value>
</alphabet_array>
</alphabet_matrix>
</scores>
<probabilities>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.772727</value>
<value letter_id="G">0.227273</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">1.000000</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">0.863636</value>
<value letter_id="T">0.136364</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.090909</value>
<value letter_id="G">0.045455</value>
<value letter_id="T">0.863636</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.590909</value>
<value letter_id="C">0.181818</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.227273</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.136364</value>
<value letter_id="C">0.727273</value>
<value letter_id="G">0.136364</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.181818</value>
<value letter_id="C">0.818182</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.000000</value>
<value letter_id="G">1.000000</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.454545</value>
<value letter_id="G">0.545455</value>
<value letter_id="T">0.000000</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.409091</value>
<value letter_id="G">0.000000</value>
<value letter_id="T">0.590909</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">0.000000</value>
<value letter_id="C">0.545455</value>
<value letter_id="G">0.272727</value>
<value letter_id="T">0.181818</value>
</alphabet_array>
</alphabet_matrix>
</probabilities>
<regular_expression>
[CG]CGGT[AT]CCG[GC][TC][CG]
</regular_expression>
<contributing_sites>
<contributing_site sequence_id="sequence_27" position="34" strand="plus" pvalue="1.52e-07" >
<left_flank>ATTGTGTTTG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TTTAAGCTTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_23" position="26" strand="plus" pvalue="4.04e-07" >
<left_flank>AATGTGGATG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CCACAAAATA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_32" position="28" strand="minus" pvalue="4.58e-07" >
<left_flank>GCGGTCTCCT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>CTGCCACCTC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_37" position="27" strand="plus" pvalue="6.59e-07" >
<left_flank>TTTTTCAGGC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>GCAGCGAAGA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_45" position="34" strand="plus" pvalue="8.63e-07" >
<left_flank>TGTCTCAGAG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CGGTAGCAAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_28" position="35" strand="plus" pvalue="9.14e-07" >
<left_flank>CCGGAGCCTG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TGGCTTCAGT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_40" position="29" strand="plus" pvalue="1.32e-06" >
<left_flank>CCATCATGGT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>GTAGTGAATG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_43" position="26" strand="plus" pvalue="2.14e-06" >
<left_flank>AATGCATGGG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>CATTGGTTCT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_17" position="25" strand="minus" pvalue="2.14e-06" >
<left_flank>CCTTGCTAGT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AAAAAAAAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_24" position="26" strand="plus" pvalue="3.31e-06" >
<left_flank>TTGGAATTCC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>GCATTCCGCG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_22" position="26" strand="minus" pvalue="3.31e-06" >
<left_flank>TGGAATGACT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>GACGCTATGT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_11" position="30" strand="plus" pvalue="3.63e-06" >
<left_flank>CCAAATGCGA</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TCCGATTTTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_30" position="26" strand="plus" pvalue="3.88e-06" >
<left_flank>GCTATCGTTG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>CTCCTTGAAT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_41" position="29" strand="minus" pvalue="6.00e-06" >
<left_flank>GTTTCAGAGT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>CAACGTTTTT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_29" position="27" strand="minus" pvalue="7.09e-06" >
<left_flank>TAGACGCGTA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>TGCGGCGGCT</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_31" position="29" strand="minus" pvalue="7.95e-06" >
<left_flank>CACATTTCGC</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>ATCTTGCAGC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_39" position="30" strand="plus" pvalue="1.02e-05" >
<left_flank>TTCTCTGTTG</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
</site>
<right_flank>AGGTCTGTTA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_25" position="19" strand="minus" pvalue="1.16e-05" >
<left_flank>TCGCGTAGGT</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>TTCCAAGAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_3" position="57" strand="minus" pvalue="1.44e-05" >
<left_flank>AACGAAAATT</left_flank>
<site>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>AAATTTGCCC</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_13" position="28" strand="minus" pvalue="2.74e-05" >
<left_flank>TAATCGATTA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>CACGAACTGG</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_10" position="30" strand="minus" pvalue="3.08e-05" >
<left_flank>GCCAGCTAAA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="T"/>
</site>
<right_flank>TTGAGCTAAA</right_flank>
</contributing_site>
<contributing_site sequence_id="sequence_0" position="21" strand="minus" pvalue="4.75e-05" >
<left_flank>ATTGATGGCA</left_flank>
<site>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="A"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="G"/>
<letter_ref letter_id="C"/>
<letter_ref letter_id="T"/>
<letter_ref letter_id="G"/>
</site>
<right_flank>GCCGTTACGT</right_flank>
</contributing_site>
</contributing_sites>
</motif>
<motif id="motif_2" name="2" width="8" sites="19" ic="11.6" re="11.4" llr="150" e_value="5.5e+003" bayes_threshold="7.98143" elapsed_time="2.451627">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="A">-1089</value>
<value letter_id="C">-21</value>
<value letter_id="G">-1089</value>
<value letter_id="T">163</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1089</value>
<value letter_id="C">-1089</value>
<value letter_id="G">-1089</value>
<value letter_id="T">197</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1089</value>
<value letter_id="C">-1089</value>
<value letter_id="G">-1089</value>
<value letter_id="T">197</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-228</value>
<value letter_id="C">-1089</value>
<value letter_id="G">-1089</value>
<value letter_id="T">189</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1089</value>
<value letter_id="C">-1089</value>
<value letter_id="G">-1089</value>
<value letter_id="T">197</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-228</value>
<value letter_id="C">79</value>
<value letter_id="G">-1089</value>
<value letter_id="T">104</value>
</alphabet_array>
<alphabet_array>
<value letter_id="A">-1089</value>
<value letter_id="C">137</value>
<value letter_id="G">-1089</value>
<value letter_id="T">53</value>
</alphabet_array>
<alphabet_array>